class action_defs():
    NO_OP = 'NO_OP'
    # SCV ACTIONS
    HARVEST_MINERALS = 'HARVEST_MINERALS'
    HARVEST_GAS = 'HARVEST_GAS'

    # TRAINING ACTIONS
    TRAIN_SCV = 'TRAIN_SCV'
    TRAIN_MARINE = 'TRAIN_MARINE'

    # BUILD ACTIONS
    BUILD_BARRACKS = 'BUILD_BARRACKS'
    BUILD_SUPPLY_DEPOT = 'BUILD_SUPPLY_DEPOT'

    # AGGREGATE ACTIONS
    ALL_COMBAT_UNITS_ATTACK = 'ALL_COMBAT_UNITS_ATTACK'
    ALL_SCVS_ATTACK = 'ALL_SCVS_ATTACK'
    ALL_UNITS_ATTACK = 'ALL_UNITS_ATTACK'

    #ACTION GROUPINGS
    ALL_ACTIONS = [NO_OP, HARVEST_MINERALS, HARVEST_GAS, TRAIN_SCV, TRAIN_MARINE, ALL_COMBAT_UNITS_ATTACK, ALL_SCVS_ATTACK, ALL_UNITS_ATTACK]

    # ACTIONS FOR INDIVIDUAL UNITS
    MOVE_UP = 'MOVE_UP'
    MOVE_RIGHT = 'MOVE_RIGHT'
    MOVE_DOWN = 'MOVE_DOWN'
    MOVE_LEFT = 'MOVE_LEFT'
    ATTACK_CLOSEST_ENEMY = 'ATTACK_CLOSEST_ENEMY'

    MARINE_ACTIONS = [NO_OP, MOVE_UP, MOVE_RIGHT, MOVE_LEFT, MOVE_DOWN, ATTACK_CLOSEST_ENEMY]
    ATTACK = 'ATTACK'
    MOVE = 'MOVE'
    SCV_ACTIONS = [NO_OP, HARVEST_MINERALS]
    MARINE_ACTIONS = [NO_OP, ATTACK, MOVE]

    #ACTION IDS
    # NOT CERTAIN THESE ARE NECESSARY BUT GYM LIKES NUMBERS
    ACTION_IDS = {NO_OP: 0, MOVE_UP: 1, MOVE_RIGHT: 2, MOVE_DOWN: 3, MOVE_LEFT: 4, HARVEST_MINERALS: 5, HARVEST_GAS: 6, TRAIN_SCV: 7, TRAIN_MARINE: 8,
                    ALL_COMBAT_UNITS_ATTACK: 9, ALL_SCVS_ATTACK: 10}